 source "https://rubygems.org"
 ruby '2.5.3'
 gem 'rspec'
 gem 'pry'
 gem 'rubocop', '~> 0.57.2'
 gem 'dotenv'
 gem 'twitter'
 gem 'nokogiri'
 gem 'launchy'
 gem 'watir'
 gem 'selenium-webdriver'
 gem 'csv'
 gem 'json'
 gem 'google_drive'